# Curated Brewfile migrated from nix-darwin / nix-homebrew.
# Intentionally no cleanup: never remove undeclared packages.

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "hashicorp/tap"
tap "joshavant/tap"
tap "cirruslabs/cli"
tap "mutagen-io/mutagen"

# Core runtimes / managers
brew "chezmoi"
brew "mise"
brew "uv"
brew "direnv"
brew "pipx"
brew "python@3.14"

# Shell / editor / git
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-fast-syntax-highlighting"
brew "tmux"
brew "neovim"
brew "git"
brew "gh"
brew "git-delta"
brew "ripgrep"
brew "fd"
brew "bat"
brew "fzf"
brew "eza"
brew "tree"
brew "jq"
brew "httpie"
brew "htop"
brew "glances"
brew "shellcheck"
brew "yamllint"
brew "ruff"
brew "trash-cli"
brew "coreutils"
brew "mas"
brew "wget"
brew "curl"

# Dev tooling
brew "dagger"
brew "cmake"
brew "ninja"
brew "pkg-config"
brew "pandoc"
brew "graphviz"
brew "plantuml"
brew "imagemagick"
brew "ffmpeg"
brew "lame"
brew "chromaprint"
brew "taglib"
brew "cocoapods"
brew "xcodegen"
brew "npm-check-updates"
brew "podman"
brew "podman-compose"
brew "qemu"
brew "diffoscope"
brew "gitleaks"
brew "semgrep"
brew "tokei"
brew "typos-cli"
brew "sccache"
brew "gnupg"
brew "age"
brew "sops"
brew "nmap"
brew "mitmproxy"
brew "apktool"
brew "bento4"
brew "witr"

# Optional security audit
brew "lynis"

# Casks
cask "macfuse"
cask "zoom"
cask "appcleaner"
cask "basictex"
cask "gimp"
cask "iterm2"
cask "logi-options+"
cask "thunderbird"
cask "calibre"
cask "orcaslicer"
cask "ollama-app"
cask "phoenix"
cask "sdformatter"
cask "steam"
cask "the-unarchiver"
cask "telegram"
cask "inkscape"
cask "dbeaver-community"
cask "podman-desktop"
cask "hex-fiend"

# Fonts
cask "font-chivo-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace"
cask "font-noto-color-emoji"
